name: Bench

on:
  workflow_call:
    inputs:
      go:
        description: 'Go version'
        default: 1.18
        required: false
        type: string
      cache-prefix:
        description: 'Cache prefix'
        default: "test"
        required: false
        type: string
      count:
        description: 'Number of benchmarks'
        default: 15
        required: true
        type: number
      benchmark:
        description: 'Benchmark name regex'
        default: "Benchmark"
        required: true
        type: string
      cpuprofile:
        description: 'CPU profile'
        default: false
        required: false
        type: boolean
      memprofile:
        description: 'Memory profile'
        default: false
        required: false
        type: boolean


jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version: ${{ inputs.go }}

      - name: Download dependencies
        run: go mod download && go mod tidy

      - name: Run benchmarks
        run: >-
          go test
          -v
          -count=${{ inputs.count }}
          -bench=${{ inputs.benchmark }}
          -cpuprofile=${{ inputs.cpuprofile && "cpuprofile.out" }}
          -memprofile=${{ inputs.memprofile && "memprofile.out" }}
          -run=$^ | tee bench.txt

      - name: Upload artifact (profile)
        uses: actions/upload-artifact@v3
        with:
          name: profile
          path: "*profile.out"
          if-no-files-found: error
          retention-days: 1

      - name: Upload artifact (bench.txt)
        uses: actions/upload-artifact@v3
        with:
          name: bench.txt
          path: bench.txt
          if-no-files-found: error
          retention-days: 1